version: '2'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/rest

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/app

  mongo:
    build: .
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/db
    command: /usr/bin/mongod --bind_ip 0.0.0.0

    